//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func validate() throws {

  }


  /// This `_R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 7 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// ja translation: はい
      ///
      /// Key: alert.button.commonYes
      ///
      /// Locales: ja, en
      var alertButtonCommonYes: RswiftResources.StringResource { .init(key: "alert.button.commonYes", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ja translation: ファイルを削除しますか？
      ///
      /// Key: alert.title.confirmDeletion
      ///
      /// Locales: ja, en
      var alertTitleConfirmDeletion: RswiftResources.StringResource { .init(key: "alert.title.confirmDeletion", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ja translation: 呪文をコピー
      ///
      /// Key: button.copyPrompt
      ///
      /// Locales: ja, en
      var buttonCopyPrompt: RswiftResources.StringResource { .init(key: "button.copyPrompt", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ja translation: 削除
      ///
      /// Key: button.deleteImage
      ///
      /// Locales: ja, en
      var buttonDeleteImage: RswiftResources.StringResource { .init(key: "button.deleteImage", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ja translation: フォルダを開く
      ///
      /// Key: button.openFolder
      ///
      /// Locales: ja, en
      var buttonOpenFolder: RswiftResources.StringResource { .init(key: "button.openFolder", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ja translation: 開く
      ///
      /// Key: button.openImage
      ///
      /// Locales: ja, en
      var buttonOpenImage: RswiftResources.StringResource { .init(key: "button.openImage", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ja translation: プレビュー
      ///
      /// Key: button.preview
      ///
      /// Locales: ja, en
      var buttonPreview: RswiftResources.StringResource { .init(key: "button.preview", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }
    }
  }
}